name: my_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - llvm-openmp  # For LightGBM on macOS
  - lightgbm>=3.0
  - pip
  - pip:
      - kedro~=0.18.14
      - black
      - flake8<5.0,>=3.7.9
      - ipython
      - isort~=5.0
      - jupyter~=1.0
      - jupyterlab<3.6.0,>=3.0
      - kedro-telemetry~=0.2.0
      - nbstripout~=0.4
      - pytest-cov~=3.0
      - pytest-mock<2.0,>=1.7.1
      - pytest~=7.2
      - tra itlets<5.10.0
      - pycaret>=3.0
      # other pip dependencies as needed
